### ISSUE TITLE
Wordpress?

### ISSUE THREAD

**Issue by beauvais** [maraujop/requests-oauth2#8]
This is a great idea, and I get the documentation, but when working with Wordpress' new(ish) JSON API, I'm getting all sorts of odd errors.

Has anyone got requests-OAuth2 to work with WP's RESE API?

**Comment by rollcat** [comment]
@beauvais I'd love to help, but can you provide a traceback, example code showing the issue, something for me to work with?

**Comment by beauvais** [comment]
Hi, sorry – I never closed this. It's been 5 years, and I can't remember exactly what I was doing with it back then.

**Comment by rollcat** [comment]
Sure, thanks for the update.
